### ISSUE TITLE
Problem with sub nodes and references?

### ISSUE THREAD

**Issue by pwFoo** [Dletta/visualGraph#2]
@Dletta 
I try to show references to sub-nodes and display object values, but get an error message
```
d3.v4.min.js:2 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#<STARTNODE>/<SUBNODE>/4973947925444637' is not a valid selector.
    at Object.ct [as select] (https://d3js.org/d3.v4.min.js:2:9416)
    at SVGCircleElement.detail (https://<DOMAIN_VISUALGRAPH>/visualGraph.js:106:21)
    at SVGCircleElement.<anonymous> (https://d3js.org/d3.v4.min.js:2:8198)
```

**Comment by pwFoo** [comment]
Maybe something changed in new(est) gun?
Path like element IDs with slashes?
```
#<STARTNODE>/<SUBNODE>/4973947925444637
```

**Comment by Dletta** [comment]
Looks like it's related to a d3 selector method and maybe a string
converter there. I will have a quick look and will do a quick update commit
to latest versions

**Comment by Dletta** [comment]
This issue is solved.
It was an issue where d3 and it's friendly jquery couldn't cope with the new #soul/subsoul, meaning the dash was not recognized as an id in the selector.
I also unpinned gun versions and it is now running on the latest version. There seems to be no issue there.

**Comment by pwFoo** [comment]
HI @Dletta 
Problem still exists. If I show a sub node as start point I see all direct child nodes. 
```
"parent/sub" -> 3 children
```

If I start with des parent node I see just 2 of 3 child nodes at my sub node?
```
parent -> sub -> 2 of 3 children
```

Still same error if I try to show node properties by click
```
d3.v4.min.js:2 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#<PARENT>/<SUB>/98039408' is not a valid selector.
    at Object.ct [as select] (https://d3js.org/d3.v4.min.js:2:9416)
    at SVGCircleElement.detail (https://<DOMAIN>/visualGraph.js:106:21)
    at SVGCircleElement.<anonymous> (https://d3js.org/d3.v4.min.js:2:8198)
```

Still "/" in dom element id
```
<circle id="<PARENT>/<SUB>" r="3" fill="rgb(120,0,0)" cx="350.4860356812201" cy="244.6140260048059"><title><PARENT>/<SUB></title></circle>
```

**Comment by Dletta** [comment]
Can you show me your graph structure?

I switched away from querySelector, maybe I missed one of the d3.selects. (I simply changed any d3.select to document.getElementById, so feel free to see where I missed it and make a PR.)

**Comment by pwFoo** [comment]
I build the graph with demo data.
```
gun.get("APP_NAME").get('TABLE').map().once((item, soul) => console.log(soul, item))
c {_: {…}}
VM585:1 1586901425 {_: {…}, id: 2, name: 'ITEM_2', value: 'second'}
VM585:1 2213577188 {_: {…}, id: 1, name: 'ITEM_1', value: 'first'}
VM585:1 3227399464 {_: {…}, id: 3, name: 'ITEM_3', value: 'third'}
```

Showing full graph from APP_NAME *ITEM_3* is missing!
![image](https://user-images.githubusercontent.com/333408/159479875-e990346d-febf-4260-b967-60a081ac13e4.png)

Starting with APP_NAME/TABLE all items are shown.
![image](https://user-images.githubusercontent.com/333408/159480108-3866def4-4559-411e-b921-0e563340ceff.png)

Error if I click ITEM_3
```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#APP_NAME/TABLE/3227399464' is not a valid selector.
    at Object.ct [as select] (https://d3js.org/d3.v4.min.js:2:9416)
    at SVGCircleElement.detail (https://<DOMAIN>/visualGraph.js:106:21)
    at SVGCircleElement.<anonymous> (https://d3js.org/d3.v4.min.js:2:8198)
```

**Comment by pwFoo** [comment]
@Dletta Have you found a solution for that id problem?

**Comment by pwFoo** [comment]
Updated my container with visualGraph. Looks like I used an older version...
But new error with latest 
```
visualGraph.js:264 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at Object.dfs.search (visualGraph.js:264:9)
    at HTMLButtonElement.start (visualGraph.js:185:7)
dfs.search @ visualGraph.js:264
start @ visualGraph.js:185
```

**Comment by pwFoo** [comment]
@Dletta 
Tested with a new deployed version with the same problem.

It works fine to show structure like 
```
container -> many items
```

But if container is a sub-node some items are missing!
```
app1 -> container -> 2 of 4 items
```

Wie it doesn't render all container items recursive?

**Comment by Dletta** [comment]
Hmm, not sure. It's depth-first search with a limit, I gotta check why it's
not continuing, maybe I will add a limit control and some console logs to
better indicate if the limit is reached.

The error seems to indicate it reaches a point where it thinks it has a
reference to a child, but it can't get from it

**Comment by Dletta** [comment]
@pwFoo Still interested in a fix for this?
